#!/bin/bash
set -e

# Obter o usuário atual que está removendo o pacote
USER=$(logname)

# Configurar o XDG_RUNTIME_DIR para o usuário
XDG_RUNTIME_DIR="/run/user/$(id -u $USER)"
export XDG_RUNTIME_DIR

# Executar os comandos no contexto do usuário
su - "$USER" -c "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR systemctl --user stop md-tracker-search-provider.service || true"
su - "$USER" -c "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR systemctl --user disable md-tracker-search-provider.service || true"
su - "$USER" -c "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR systemctl --user daemon-reload"
